services:
  - type: web
    name: demo
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist/demo/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html